//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class cidades
{
    public Nullable<int> cd_uf { get; set; }
    public int cd_cidade { get; set; }
    public string ds_cidade_nome { get; set; }

    public virtual uf uf { get; set; }
}

public partial class TB_ADMIN_USER
{
    public TB_ADMIN_USER()
    {
        this.TB_PERMISSAO_ADMIN = new HashSet<TB_PERMISSAO_ADMIN>();
    }

    public int id_user { get; set; }
    public string nm_user { get; set; }
    public string ds_login { get; set; }
    public string ds_password { get; set; }
    public string ds_email { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual ICollection<TB_PERMISSAO_ADMIN> TB_PERMISSAO_ADMIN { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_AREA_MEDICA_CURSO
{
    public TB_AREA_MEDICA_CURSO()
    {
        this.TB_AREA_MEDICA_CURSO_ESPECIALIDADE = new HashSet<TB_AREA_MEDICA_CURSO_ESPECIALIDADE>();
        this.TB_AREA_MEDICA_CURSO_HOSPITAL = new HashSet<TB_AREA_MEDICA_CURSO_HOSPITAL>();
    }

    public int id { get; set; }
    public string ds_curso { get; set; }
    public int id_hospital { get; set; }
    public System.DateTime dt_curso { get; set; }
    public string vl_curso { get; set; }
    public string ds_descricao { get; set; }
    public int id_status { get; set; }
    public string ds_horario { get; set; }
    public Nullable<System.DateTime> dt_inscricao { get; set; }
    public string ds_local { get; set; }
    public string ds_link_curso { get; set; }
    public string ds_minidesc { get; set; }
    public string ds_email { get; set; }
    public string ds_telefone { get; set; }
    public string ds_box2_titulo { get; set; }
    public string ds_box2_desc { get; set; }

    public virtual ICollection<TB_AREA_MEDICA_CURSO_ESPECIALIDADE> TB_AREA_MEDICA_CURSO_ESPECIALIDADE { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual ICollection<TB_AREA_MEDICA_CURSO_HOSPITAL> TB_AREA_MEDICA_CURSO_HOSPITAL { get; set; }
}

public partial class TB_AREA_MEDICA_CURSO_ESPECIALIDADE
{
    public int id_curso_especialidade { get; set; }
    public int id_area_medica_curso { get; set; }
    public int id_especialidade { get; set; }

    public virtual TB_EPSECIALIDADE TB_EPSECIALIDADE { get; set; }
    public virtual TB_AREA_MEDICA_CURSO TB_AREA_MEDICA_CURSO { get; set; }
}

public partial class TB_AREA_MEDICA_CURSO_HOSPITAL
{
    public int id_curso_hospital { get; set; }
    public int id_curso { get; set; }
    public int id_hospital { get; set; }

    public virtual TB_AREA_MEDICA_CURSO TB_AREA_MEDICA_CURSO { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_CONTEUDO_METATAGS
{
    public int id_metatag { get; set; }
    public int id_conteudo { get; set; }
    public string ds_description { get; set; }
    public string ds_keywords { get; set; }
    public string ds_pagina { get; set; }
    public int id_hospital { get; set; }
}

public partial class TB_CONTEUDO_PAGINA_FIXA
{
    public int id_pagina_fixa { get; set; }
    public int id_sessao { get; set; }
    public int id_hospital { get; set; }
    public string ds_link { get; set; }
    public string ds_desc_menu { get; set; }
    public string ds_titulo { get; set; }
    public bool ds_visivel { get; set; }
}

public partial class TB_CONTROLE_NOTICIA
{
    public TB_CONTROLE_NOTICIA()
    {
        this.TB_PORTAL_CONTEUDO = new HashSet<TB_PORTAL_CONTEUDO>();
    }

    public int id_noticia { get; set; }
    public Nullable<System.DateTime> dt_noticia { get; set; }
    public Nullable<int> id_status { get; set; }
    public Nullable<int> id_usuario { get; set; }

    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual ICollection<TB_PORTAL_CONTEUDO> TB_PORTAL_CONTEUDO { get; set; }
}

public partial class TB_DEMOSTRATIVO_FINANCEIRO
{
    public int idDemostrativo { get; set; }
    public string dsDemostrativo { get; set; }
    public string dsArquivo { get; set; }
    public int idStatus { get; set; }
    public Nullable<System.DateTime> dtDemonstrativo { get; set; }
}

public partial class TB_EPSECIALIDADE
{
    public TB_EPSECIALIDADE()
    {
        this.TB_ESPECIALIDADE_HOSPITAL = new HashSet<TB_ESPECIALIDADE_HOSPITAL>();
        this.TB_AREA_MEDICA_CURSO_ESPECIALIDADE = new HashSet<TB_AREA_MEDICA_CURSO_ESPECIALIDADE>();
    }

    public int id_especialidade { get; set; }
    public string nm_especialidade { get; set; }
    public string ds_especialidade { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual ICollection<TB_ESPECIALIDADE_HOSPITAL> TB_ESPECIALIDADE_HOSPITAL { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual ICollection<TB_AREA_MEDICA_CURSO_ESPECIALIDADE> TB_AREA_MEDICA_CURSO_ESPECIALIDADE { get; set; }
}

public partial class TB_ESPECIALIDADE_CONSULTORIOS
{
    public int idEspecialidade_Consutorios { get; set; }
    public int idHosp { get; set; }
    public string dsNome { get; set; }
    public string dsInfo { get; set; }
}

public partial class TB_ESPECIALIDADE_HOSPITAL
{
    public int id_especialidade_hospital { get; set; }
    public int id_hospital { get; set; }
    public int id_especialidade { get; set; }

    public virtual TB_EPSECIALIDADE TB_EPSECIALIDADE { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_EXAME
{
    public TB_EXAME()
    {
        this.TB_EXAME_HOSPITAL = new HashSet<TB_EXAME_HOSPITAL>();
    }

    public int id_exame { get; set; }
    public string nm_exame { get; set; }
    public string ds_exame { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual ICollection<TB_EXAME_HOSPITAL> TB_EXAME_HOSPITAL { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_EXAME_HOSPITAL
{
    public int id_exame_hospital { get; set; }
    public int id_hospital { get; set; }
    public int id_exame { get; set; }

    public virtual TB_EXAME TB_EXAME { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_FORMULARIO_EXAMES
{
    public int id_exames_imagem { get; set; }
    public int id_hospital { get; set; }
    public string ds_nome { get; set; }
    public string ds_data_nascimento { get; set; }
    public string ds_telefone_fixo { get; set; }
    public string ds_telefone_celular { get; set; }
    public System.DateTime dt_atendimento { get; set; }
    public string ds_atendimento { get; set; }
    public string ds_observacao { get; set; }
    public System.DateTime dt_solicitacao { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_FORMULARIOS
{
    public int id_formulario { get; set; }
    public Nullable<int> id_hospital { get; set; }
    public Nullable<int> id_status { get; set; }
    public string nm_formulário { get; set; }
    public string ds_arquivo { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_FOTO_BEBE
{
    public int id_foto { get; set; }
    public System.DateTime dt_nascimento { get; set; }
    public System.DateTime dt_cadastro { get; set; }
    public string ds_nome_mae { get; set; }
    public string ds_nome_pai { get; set; }
    public string ds_nome_bebe { get; set; }
    public double nu_peso { get; set; }
    public double nu_estatura { get; set; }
    public string ds_obstreta { get; set; }
    public string ds_pediatra { get; set; }
    public int id_hospital { get; set; }
    public string ds_foto_bebe { get; set; }
    public string ds_foto_retrato { get; set; }
    public string ds_foto_thumb { get; set; }
    public int fg_status { get; set; }
}

public partial class TB_HOSPITAL
{
    public TB_HOSPITAL()
    {
        this.TB_ESPECIALIDADE_HOSPITAL = new HashSet<TB_ESPECIALIDADE_HOSPITAL>();
        this.TB_EXAME_HOSPITAL = new HashSet<TB_EXAME_HOSPITAL>();
        this.TB_PERMISSAO_ADMIN = new HashSet<TB_PERMISSAO_ADMIN>();
        this.TB_PRONTOSOCORRO_HOSPITAL = new HashSet<TB_PRONTOSOCORRO_HOSPITAL>();
        this.TB_FORMULARIOS = new HashSet<TB_FORMULARIOS>();
        this.TB_NEWSLETTER = new HashSet<TB_NEWSLETTER>();
        this.TB_AREA_MEDICA_CURSO = new HashSet<TB_AREA_MEDICA_CURSO>();
        this.TB_PORTAL_CONTEUDO = new HashSet<TB_PORTAL_CONTEUDO>();
        this.TB_PORTAL_CONTEUDO_HOSPITAL = new HashSet<TB_PORTAL_CONTEUDO_HOSPITAL>();
        this.TB_AREA_MEDICA_CURSO_HOSPITAL = new HashSet<TB_AREA_MEDICA_CURSO_HOSPITAL>();
        this.TB_PORTAL_SLIDER = new HashSet<TB_PORTAL_SLIDER>();
        this.TB_PORTAL_BANNER = new HashSet<TB_PORTAL_BANNER>();
        this.TB_HOSPITAL_CORPO_CLINICO_HOSPITAL = new HashSet<TB_HOSPITAL_CORPO_CLINICO_HOSPITAL>();
        this.TB_FORMULARIO_EXAMES = new HashSet<TB_FORMULARIO_EXAMES>();
        this.TB_MEDICO_CONSULTORIOS = new HashSet<TB_MEDICO_CONSULTORIOS>();
        this.TB_MEDICO_CONSULTORIOS1 = new HashSet<TB_MEDICO_CONSULTORIOS>();
    }

    public int id_hospital { get; set; }
    public string nm_hospital { get; set; }
    public string ds_hospital { get; set; }
    public string ds_site_hospital { get; set; }
    public string ds_endereco_hospital { get; set; }
    public string nr_telefone_hospital { get; set; }
    public int id_estado { get; set; }
    public int id_status { get; set; }

    public virtual ICollection<TB_ESPECIALIDADE_HOSPITAL> TB_ESPECIALIDADE_HOSPITAL { get; set; }
    public virtual ICollection<TB_EXAME_HOSPITAL> TB_EXAME_HOSPITAL { get; set; }
    public virtual uf uf { get; set; }
    public virtual ICollection<TB_PERMISSAO_ADMIN> TB_PERMISSAO_ADMIN { get; set; }
    public virtual ICollection<TB_PRONTOSOCORRO_HOSPITAL> TB_PRONTOSOCORRO_HOSPITAL { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual ICollection<TB_FORMULARIOS> TB_FORMULARIOS { get; set; }
    public virtual ICollection<TB_NEWSLETTER> TB_NEWSLETTER { get; set; }
    public virtual ICollection<TB_AREA_MEDICA_CURSO> TB_AREA_MEDICA_CURSO { get; set; }
    public virtual ICollection<TB_PORTAL_CONTEUDO> TB_PORTAL_CONTEUDO { get; set; }
    public virtual ICollection<TB_PORTAL_CONTEUDO_HOSPITAL> TB_PORTAL_CONTEUDO_HOSPITAL { get; set; }
    public virtual ICollection<TB_AREA_MEDICA_CURSO_HOSPITAL> TB_AREA_MEDICA_CURSO_HOSPITAL { get; set; }
    public virtual ICollection<TB_PORTAL_SLIDER> TB_PORTAL_SLIDER { get; set; }
    public virtual ICollection<TB_PORTAL_BANNER> TB_PORTAL_BANNER { get; set; }
    public virtual ICollection<TB_HOSPITAL_CORPO_CLINICO_HOSPITAL> TB_HOSPITAL_CORPO_CLINICO_HOSPITAL { get; set; }
    public virtual TB_HOSPITAL_DEPT_CONTATO TB_HOSPITAL_DEPT_CONTATO { get; set; }
    public virtual ICollection<TB_FORMULARIO_EXAMES> TB_FORMULARIO_EXAMES { get; set; }
    public virtual ICollection<TB_MEDICO_CONSULTORIOS> TB_MEDICO_CONSULTORIOS { get; set; }
    public virtual ICollection<TB_MEDICO_CONSULTORIOS> TB_MEDICO_CONSULTORIOS1 { get; set; }
}

public partial class TB_HOSPITAL_CONSULTORIOS
{
    public int idHospital { get; set; }
    public string dsImagem { get; set; }
    public int fgAtivo { get; set; }
}

public partial class TB_HOSPITAL_CORPO_CLINICO
{
    public TB_HOSPITAL_CORPO_CLINICO()
    {
        this.TB_HOSPITAL_CORPO_CLINICO_HOSPITAL = new HashSet<TB_HOSPITAL_CORPO_CLINICO_HOSPITAL>();
    }

    public int id_corpo_clinico { get; set; }
    public string nm_medico { get; set; }
    public string nm_cargo { get; set; }
    public int id_especialidade { get; set; }

    public virtual ICollection<TB_HOSPITAL_CORPO_CLINICO_HOSPITAL> TB_HOSPITAL_CORPO_CLINICO_HOSPITAL { get; set; }
}

public partial class TB_HOSPITAL_CORPO_CLINICO_HOSPITAL
{
    public int id_corpo_clinico_hospital { get; set; }
    public int id_corpo_clinico { get; set; }
    public int id_hospital { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual TB_HOSPITAL_CORPO_CLINICO TB_HOSPITAL_CORPO_CLINICO { get; set; }
}

public partial class TB_HOSPITAL_DEPT_CONTATO
{
    public int id_hospital { get; set; }
    public string ds_departamento { get; set; }
    public string ds_contato { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_HOSPITAL_PORTAL
{
    public int id_hospital_portal { get; set; }
    public int id_hospital { get; set; }
    public string ds_dominio { get; set; }
    public string ds_imagem_logo { get; set; }
    public string ds_titulo_pagina { get; set; }
    public string ds_telefone { get; set; }
    public string ds_endereco_rodape { get; set; }
    public string ds_link_facebook { get; set; }
    public string ds_link_twitter { get; set; }
    public string ds_google_analytics { get; set; }
    public string ds_maps { get; set; }
    public Nullable<bool> fg_exibir { get; set; }
    public string ds_icone { get; set; }
    public string ds_css { get; set; }
    public string ds_youtube { get; set; }
    public string ds_blog { get; set; }
    public string ds_linkedin { get; set; }
}

public partial class TB_HOSPTIAL_FOTO_BEBE
{
    public int id_hospital { get; set; }
    public bool fg_foto_bebe { get; set; }
    public string ds_moldura { get; set; }
    public string ds_banner { get; set; }
    public string ds_linkbanner { get; set; }
}

public partial class TB_IDIOMA
{
    public TB_IDIOMA()
    {
        this.TB_PORTAL_SLIDER = new HashSet<TB_PORTAL_SLIDER>();
        this.TB_PORTAL_CONTEUDO = new HashSet<TB_PORTAL_CONTEUDO>();
        this.TB_PORTAL_VIDEO = new HashSet<TB_PORTAL_VIDEO>();
        this.TB_PORTAL_BANNER = new HashSet<TB_PORTAL_BANNER>();
    }

    public int id_idioma { get; set; }
    public string nm_idioma { get; set; }
    public string ds_flag { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual ICollection<TB_PORTAL_SLIDER> TB_PORTAL_SLIDER { get; set; }
    public virtual ICollection<TB_PORTAL_CONTEUDO> TB_PORTAL_CONTEUDO { get; set; }
    public virtual ICollection<TB_PORTAL_VIDEO> TB_PORTAL_VIDEO { get; set; }
    public virtual ICollection<TB_PORTAL_BANNER> TB_PORTAL_BANNER { get; set; }
}

public partial class TB_MEDICO_CONSULTORIOS
{
    public int idMedico_Consultorios { get; set; }
    public string dsNome { get; set; }
    public int idHosp { get; set; }
    public int idEspecialidade_Consutorios { get; set; }
    public string dsInfo { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL1 { get; set; }
}

public partial class TB_NEWSLETTER
{
    public int id_newsletter { get; set; }
    public Nullable<int> id_hospital { get; set; }
    public Nullable<System.DateTime> dt_data { get; set; }
    public string ds_email { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_PERMISSAO_ADMIN
{
    public int id_permissao { get; set; }
    public Nullable<int> id_user { get; set; }
    public Nullable<int> id_hospital { get; set; }

    public virtual TB_ADMIN_USER TB_ADMIN_USER { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_PORTAL_ARQUIVO
{
    public int id_arquivo { get; set; }
    public Nullable<int> id_conteudo { get; set; }
    public string mn_arquivo { get; set; }
    public string ds_arquivo { get; set; }
    public Nullable<System.DateTime> dt_arquivo { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual TB_PORTAL_CONTEUDO TB_PORTAL_CONTEUDO { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PORTAL_BANNER
{
    public int id_banner { get; set; }
    public string ds_imagem { get; set; }
    public string ds_link { get; set; }
    public string ds_descrição { get; set; }
    public Nullable<int> id_status { get; set; }
    public Nullable<int> id_idioma { get; set; }
    public Nullable<int> id_hospital { get; set; }
    public Nullable<int> id_posicao { get; set; }
    public string css_type { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual TB_IDIOMA TB_IDIOMA { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PORTAL_BANNER_CSS_TYPE
{
    public int id_banner_css_type { get; set; }
    public string ds_titulo { get; set; }
    public string ds_css { get; set; }
}

public partial class TB_PORTAL_CONTEUDO
{
    public TB_PORTAL_CONTEUDO()
    {
        this.TB_PORTAL_ARQUIVO = new HashSet<TB_PORTAL_ARQUIVO>();
        this.TB_PORTAL_CONTEUDO_HOSPITAL = new HashSet<TB_PORTAL_CONTEUDO_HOSPITAL>();
    }

    public int id_conteudo { get; set; }
    public Nullable<int> id_idioma { get; set; }
    public Nullable<int> id_status { get; set; }
    public Nullable<int> id_sessao { get; set; }
    public Nullable<int> id_tipo { get; set; }
    public Nullable<System.DateTime> dt_conteudo { get; set; }
    public Nullable<bool> ds_visivel { get; set; }
    public string nm_titulo { get; set; }
    public string ds_resumo { get; set; }
    public string ds_conteudo { get; set; }
    public string ds_imgDestaque { get; set; }
    public string ds_url { get; set; }
    public Nullable<int> id_noticia { get; set; }
    public Nullable<int> nr_edicaorevista { get; set; }
    public string ds_sessao_revista { get; set; }
    public Nullable<bool> ds_materiaDestaque { get; set; }
    public string ds_file { get; set; }
    public string nm_titulo_fonetico { get; set; }
    public string ds_resumo_fonetico { get; set; }
    public string ds_conteudo_fonetico { get; set; }
    public Nullable<int> id_hospital { get; set; }
    public string ds_email_form { get; set; }

    public virtual TB_CONTROLE_NOTICIA TB_CONTROLE_NOTICIA { get; set; }
    public virtual TB_IDIOMA TB_IDIOMA { get; set; }
    public virtual ICollection<TB_PORTAL_ARQUIVO> TB_PORTAL_ARQUIVO { get; set; }
    public virtual TB_PORTAL_EDICAO_REVISTA TB_PORTAL_EDICAO_REVISTA { get; set; }
    public virtual TB_PORTAL_SESSAO TB_PORTAL_SESSAO { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual TB_PORTAL_TIPO TB_PORTAL_TIPO { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual ICollection<TB_PORTAL_CONTEUDO_HOSPITAL> TB_PORTAL_CONTEUDO_HOSPITAL { get; set; }
}

public partial class TB_PORTAL_CONTEUDO_HOSPITAL
{
    public int id_Conteudo_Hospital { get; set; }
    public int id_conteudo { get; set; }
    public int id_hospital { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual TB_PORTAL_CONTEUDO TB_PORTAL_CONTEUDO { get; set; }
}

public partial class TB_PORTAL_EDICAO_REVISTA
{
    public TB_PORTAL_EDICAO_REVISTA()
    {
        this.TB_PORTAL_CONTEUDO = new HashSet<TB_PORTAL_CONTEUDO>();
    }

    public int id_edicao { get; set; }
    public int nr_edicao { get; set; }
    public Nullable<System.DateTime> dt_edicao { get; set; }
    public Nullable<int> id_status { get; set; }
    public string ds_imagem { get; set; }
    public string ds_arquivo { get; set; }
    public string ds_destaque { get; set; }
    public string ds_descricao { get; set; }

    public virtual ICollection<TB_PORTAL_CONTEUDO> TB_PORTAL_CONTEUDO { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PORTAL_ESPECIALISTA
{
    public TB_PORTAL_ESPECIALISTA()
    {
        this.TB_PORTAL_SAUDE_HSL_DOR = new HashSet<TB_PORTAL_SAUDE_HSL_DOR>();
    }

    public int id_especialista { get; set; }
    public string nm_especialista { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual ICollection<TB_PORTAL_SAUDE_HSL_DOR> TB_PORTAL_SAUDE_HSL_DOR { get; set; }
}

public partial class TB_PORTAL_MENU_ORDEM
{
    public int id_sessao { get; set; }
    public int id_pagina { get; set; }
    public Nullable<int> nu_ordem { get; set; }
    public int id_tipo { get; set; }
    public Nullable<int> id_hospital { get; set; }
}

public partial class TB_PORTAL_MENUFIXO
{
    public int id_menufixo { get; set; }
    public string ds_menufixo { get; set; }
    public string ds_linkmenu { get; set; }
    public Nullable<int> id_sessao { get; set; }

    public virtual TB_PORTAL_SESSAO TB_PORTAL_SESSAO { get; set; }
}

public partial class TB_PORTAL_PROGRAMETES
{
    public int id_programete { get; set; }
    public string nm_titulo { get; set; }
    public string ds_video { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PORTAL_PROGRAMETES_DESTAQUE
{
    public int id_programete { get; set; }
    public string nm_titulo { get; set; }
    public string ds_video { get; set; }
}

public partial class TB_PORTAL_PROGRAMETES_TEXTO
{
    public int id_programete { get; set; }
    public string ds_texto { get; set; }
}

public partial class TB_PORTAL_SAUDE_HSL_DOR
{
    public int id_saude { get; set; }
    public string nm_titulo { get; set; }
    public Nullable<int> id_espedcialista { get; set; }
    public Nullable<int> id_tema { get; set; }
    public Nullable<int> id_status { get; set; }
    public string ds_audio { get; set; }

    public virtual TB_PORTAL_ESPECIALISTA TB_PORTAL_ESPECIALISTA { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual TB_PORTAL_TEMA TB_PORTAL_TEMA { get; set; }
}

public partial class TB_PORTAL_SESSAO
{
    public TB_PORTAL_SESSAO()
    {
        this.TB_PORTAL_CONTEUDO = new HashSet<TB_PORTAL_CONTEUDO>();
        this.TB_PORTAL_MENUFIXO = new HashSet<TB_PORTAL_MENUFIXO>();
    }

    public int id_sessao { get; set; }
    public string nm_sessao { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual ICollection<TB_PORTAL_CONTEUDO> TB_PORTAL_CONTEUDO { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual ICollection<TB_PORTAL_MENUFIXO> TB_PORTAL_MENUFIXO { get; set; }
}

public partial class TB_PORTAL_SLIDER
{
    public int id_slider { get; set; }
    public string ds_imagem { get; set; }
    public string ds_link { get; set; }
    public Nullable<int> id_status { get; set; }
    public Nullable<int> id_idioma { get; set; }
    public Nullable<int> id_hospital { get; set; }
    public Nullable<int> nu_ordem { get; set; }

    public virtual TB_IDIOMA TB_IDIOMA { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
}

public partial class TB_PORTAL_TEMA
{
    public TB_PORTAL_TEMA()
    {
        this.TB_PORTAL_SAUDE_HSL_DOR = new HashSet<TB_PORTAL_SAUDE_HSL_DOR>();
    }

    public int id_tema { get; set; }
    public string nm_tema { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual ICollection<TB_PORTAL_SAUDE_HSL_DOR> TB_PORTAL_SAUDE_HSL_DOR { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PORTAL_TIPO
{
    public TB_PORTAL_TIPO()
    {
        this.TB_PORTAL_CONTEUDO = new HashSet<TB_PORTAL_CONTEUDO>();
    }

    public int id_tipo { get; set; }
    public string nm_tipo { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual ICollection<TB_PORTAL_CONTEUDO> TB_PORTAL_CONTEUDO { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PORTAL_VIDEO
{
    public int id_video { get; set; }
    public string ds_nome { get; set; }
    public string ds_video { get; set; }
    public int id_status { get; set; }
    public int id_idioma { get; set; }

    public virtual TB_IDIOMA TB_IDIOMA { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PRONTOSOCORRO
{
    public TB_PRONTOSOCORRO()
    {
        this.TB_PRONTOSOCORRO_HOSPITAL = new HashSet<TB_PRONTOSOCORRO_HOSPITAL>();
    }

    public int id_prontosocorro { get; set; }
    public string nm_prontosocorro { get; set; }
    public string ds_prontosocorro { get; set; }
    public Nullable<int> id_status { get; set; }

    public virtual ICollection<TB_PRONTOSOCORRO_HOSPITAL> TB_PRONTOSOCORRO_HOSPITAL { get; set; }
    public virtual TB_STATUS TB_STATUS { get; set; }
}

public partial class TB_PRONTOSOCORRO_HOSPITAL
{
    public int id_prontosocorro_hospital { get; set; }
    public int id_hospital { get; set; }
    public int id_prontosocorro { get; set; }

    public virtual TB_HOSPITAL TB_HOSPITAL { get; set; }
    public virtual TB_PRONTOSOCORRO TB_PRONTOSOCORRO { get; set; }
}

public partial class TB_STATUS
{
    public TB_STATUS()
    {
        this.TB_ADMIN_USER = new HashSet<TB_ADMIN_USER>();
        this.TB_EPSECIALIDADE = new HashSet<TB_EPSECIALIDADE>();
        this.TB_EXAME = new HashSet<TB_EXAME>();
        this.TB_HOSPITAL = new HashSet<TB_HOSPITAL>();
        this.TB_IDIOMA = new HashSet<TB_IDIOMA>();
        this.TB_PRONTOSOCORRO = new HashSet<TB_PRONTOSOCORRO>();
        this.TB_PORTAL_SLIDER = new HashSet<TB_PORTAL_SLIDER>();
        this.TB_CONTROLE_NOTICIA = new HashSet<TB_CONTROLE_NOTICIA>();
        this.TB_PORTAL_ARQUIVO = new HashSet<TB_PORTAL_ARQUIVO>();
        this.TB_PORTAL_CONTEUDO = new HashSet<TB_PORTAL_CONTEUDO>();
        this.TB_PORTAL_EDICAO_REVISTA = new HashSet<TB_PORTAL_EDICAO_REVISTA>();
        this.TB_PORTAL_SESSAO = new HashSet<TB_PORTAL_SESSAO>();
        this.TB_PORTAL_TIPO = new HashSet<TB_PORTAL_TIPO>();
        this.TB_FORMULARIOS = new HashSet<TB_FORMULARIOS>();
        this.TB_PORTAL_ESPECIALISTA = new HashSet<TB_PORTAL_ESPECIALISTA>();
        this.TB_PORTAL_SAUDE_HSL_DOR = new HashSet<TB_PORTAL_SAUDE_HSL_DOR>();
        this.TB_PORTAL_TEMA = new HashSet<TB_PORTAL_TEMA>();
        this.TB_PORTAL_PROGRAMETES = new HashSet<TB_PORTAL_PROGRAMETES>();
        this.TB_PORTAL_VIDEO = new HashSet<TB_PORTAL_VIDEO>();
        this.TB_AREA_MEDICA_CURSO = new HashSet<TB_AREA_MEDICA_CURSO>();
        this.TB_PORTAL_BANNER = new HashSet<TB_PORTAL_BANNER>();
    }

    public int id_status { get; set; }
    public string nm_status { get; set; }

    public virtual ICollection<TB_ADMIN_USER> TB_ADMIN_USER { get; set; }
    public virtual ICollection<TB_EPSECIALIDADE> TB_EPSECIALIDADE { get; set; }
    public virtual ICollection<TB_EXAME> TB_EXAME { get; set; }
    public virtual ICollection<TB_HOSPITAL> TB_HOSPITAL { get; set; }
    public virtual ICollection<TB_IDIOMA> TB_IDIOMA { get; set; }
    public virtual ICollection<TB_PRONTOSOCORRO> TB_PRONTOSOCORRO { get; set; }
    public virtual ICollection<TB_PORTAL_SLIDER> TB_PORTAL_SLIDER { get; set; }
    public virtual ICollection<TB_CONTROLE_NOTICIA> TB_CONTROLE_NOTICIA { get; set; }
    public virtual ICollection<TB_PORTAL_ARQUIVO> TB_PORTAL_ARQUIVO { get; set; }
    public virtual ICollection<TB_PORTAL_CONTEUDO> TB_PORTAL_CONTEUDO { get; set; }
    public virtual ICollection<TB_PORTAL_EDICAO_REVISTA> TB_PORTAL_EDICAO_REVISTA { get; set; }
    public virtual ICollection<TB_PORTAL_SESSAO> TB_PORTAL_SESSAO { get; set; }
    public virtual ICollection<TB_PORTAL_TIPO> TB_PORTAL_TIPO { get; set; }
    public virtual ICollection<TB_FORMULARIOS> TB_FORMULARIOS { get; set; }
    public virtual ICollection<TB_PORTAL_ESPECIALISTA> TB_PORTAL_ESPECIALISTA { get; set; }
    public virtual ICollection<TB_PORTAL_SAUDE_HSL_DOR> TB_PORTAL_SAUDE_HSL_DOR { get; set; }
    public virtual ICollection<TB_PORTAL_TEMA> TB_PORTAL_TEMA { get; set; }
    public virtual ICollection<TB_PORTAL_PROGRAMETES> TB_PORTAL_PROGRAMETES { get; set; }
    public virtual ICollection<TB_PORTAL_VIDEO> TB_PORTAL_VIDEO { get; set; }
    public virtual ICollection<TB_AREA_MEDICA_CURSO> TB_AREA_MEDICA_CURSO { get; set; }
    public virtual ICollection<TB_PORTAL_BANNER> TB_PORTAL_BANNER { get; set; }
}

public partial class uf
{
    public uf()
    {
        this.cidades = new HashSet<cidades>();
        this.TB_HOSPITAL = new HashSet<TB_HOSPITAL>();
    }

    public int cd_uf { get; set; }
    public string ds_uf_sigla { get; set; }
    public string ds_uf_nome { get; set; }

    public virtual ICollection<cidades> cidades { get; set; }
    public virtual ICollection<TB_HOSPITAL> TB_HOSPITAL { get; set; }
}
